Run shfmt over it

diff --git a/mac-cleanup b/mac-cleanup
--- a/mac-cleanup
+++ b/mac-cleanup
@@ -4,14 +4,14 @@ set -E
 trap cleanup SIGINT SIGTERM ERR EXIT
 
 cleanup() {
-  trap - SIGINT SIGTERM ERR EXIT
+	trap - SIGINT SIGTERM ERR EXIT
 }
 
 # Default arguments
 update=false
 
 usage() {
-  cat <<EOF
+	cat <<EOF
 Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-u]
 
 A Mac Cleaning up Utility by fwartner
@@ -23,74 +23,77 @@ Available options:
 -v, --verbose    Print script debug info
 -u, --update     Run brew update
 EOF
-  exit
+	exit
 }
 
 setup_colors() {
-  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-    # shellcheck disable=SC2034  # Unused variables left for readability
-    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
-  else
-    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
-  fi
+	if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+		# shellcheck disable=SC2034  # Unused variables left for readability
+		NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+	else
+		NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+	fi
 }
 
 msg() {
-  echo >&2 -e "${1-}"
+	echo >&2 -e "${1-}"
 }
 
 die() {
-  local msg=$1
-  local code=${2-1} # default exit status 1
-  msg "$msg"
-  exit "$code"
+	local msg=$1
+	local code=${2-1} # default exit status 1
+	msg "$msg"
+	exit "$code"
 }
 
 parse_params() {
-  # default values of variables set from params
-  update=false
+	# default values of variables set from params
+	update=false
 
-  while :; do
-    case "${1-}" in
-    -h | --help) usage ;;
-    -v | --verbose) set -x ;;
-    --no-color) NO_COLOR=1 ;;
-    -u | --update) update=true ;; # update flag
-    -n) true ;; # This is a legacy option, now default behaviour
-    -?*) die "Unknown option: $1" ;;
-    *) break ;;
-    esac
-    shift
-  done
+	while :; do
+		case "${1-}" in
+		-h | --help) usage ;;
+		-v | --verbose) set -x ;;
+		--no-color) NO_COLOR=1 ;;
+		-u | --update) update=true ;; # update flag
+		-n) true ;;                   # This is a legacy option, now default behaviour
+		-?*) die "Unknown option: $1" ;;
+		*) break ;;
+		esac
+		shift
+	done
 
-  return 0
+	return 0
 }
 
 parse_params "$@"
 setup_colors
 
 deleteCaches() {
-    local cacheName=$1
-    shift
-    local paths=("$@")
-    echo "Initiating cleanup ${cacheName} cache..."
-    for folderPath in "${paths[@]}"; do
-        if [[ -d ${folderPath} ]]; then
-            dirSize=$(du -hs "${folderPath}" | awk '{print $1}')
-            echo "Deleting ${folderPath} to free up ${dirSize}..."
-            rm -rfv "${folderPath}" 
-        fi
-    done
+	local cacheName=$1
+	shift
+	local paths=("$@")
+	echo "Initiating cleanup ${cacheName} cache..."
+	for folderPath in "${paths[@]}"; do
+		if [[ -d ${folderPath} ]]; then
+			dirSize=$(du -hs "${folderPath}" | awk '{print $1}')
+			echo "Deleting ${folderPath} to free up ${dirSize}..."
+			rm -rfv "${folderPath}"
+		fi
+	done
 }
 
 bytesToHuman() {
-    b=${1:-0}; d=''; s=0; S=(Bytes {K,M,G,T,E,P,Y,Z}iB)
-    while ((b > 1024)); do
-        d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
-        b=$((b / 1024))
-        (( s++ ))
-    done
-    msg "$b$d ${S[$s]} of space was cleaned up"
+	b=${1:-0}
+	d=''
+	s=0
+	S=(Bytes {K,M,G,T,E,P,Y,Z}iB)
+	while ((b > 1024)); do
+		d="$(printf ".%02d" $((b % 1024 * 100 / 1024)))"
+		b=$((b / 1024))
+		((s++))
+	done
+	msg "$b$d ${S[$s]} of space was cleaned up"
 }
 
 # Ask for the administrator password upfront
@@ -99,7 +102,11 @@ sudo -v
 HOST=$(whoami)
 
 # Keep-alive sudo until `clenaup.sh` has finished
-while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+while true; do
+	sudo -n true
+	sleep 60
+	kill -0 "$$" || exit
+done 2>/dev/null &
 
 oldAvailable=$(df / | tail -1 | awk '{print $4}')
 
@@ -137,71 +144,71 @@ rm -rfv ~/Library/Developer/Xcode/Archives/* &>/dev/null
 rm -rfv ~/Library/Developer/Xcode/iOS Device Logs/* &>/dev/null
 
 if type "xcrun" &>/dev/null; then
-  msg 'Cleaning up iOS Simulators...'
-  osascript -e 'tell application "com.apple.CoreSimulator.CoreSimulatorService" to quit' &>/dev/null
-  osascript -e 'tell application "iOS Simulator" to quit' &>/dev/null
-  osascript -e 'tell application "Simulator" to quit' &>/dev/null
-  xcrun simctl shutdown all &>/dev/null
-  xcrun simctl erase all &>/dev/null
+	msg 'Cleaning up iOS Simulators...'
+	osascript -e 'tell application "com.apple.CoreSimulator.CoreSimulatorService" to quit' &>/dev/null
+	osascript -e 'tell application "iOS Simulator" to quit' &>/dev/null
+	osascript -e 'tell application "Simulator" to quit' &>/dev/null
+	xcrun simctl shutdown all &>/dev/null
+	xcrun simctl erase all &>/dev/null
 fi
 
 # support deleting gradle caches
 if [ -d "/Users/${HOST}/.gradle/caches" ]; then
-    msg 'Cleaning up Gradle cache...'
-    rm -rfv ~/.gradle/caches/ &>/dev/null
+	msg 'Cleaning up Gradle cache...'
+	rm -rfv ~/.gradle/caches/ &>/dev/null
 fi
 
 # support deleting Dropbox Cache
 if [ -d "/Users/${HOST}/Dropbox" ]; then
-    msg 'Clearing Dropbox 📦 Cache Files...'
-    sudo rm -rfv ~/Dropbox/.dropbox.cache/* &>/dev/null
+	msg 'Clearing Dropbox 📦 Cache Files...'
+	sudo rm -rfv ~/Dropbox/.dropbox.cache/* &>/dev/null
 fi
 
 msg 'Clearing Google Drive File Stream Cache Files...'
 killall "Google Drive File Stream"
 rm -rfv ~/Library/Application\ Support/Google/DriveFS/[0-9a-zA-Z]*/content_cache &>/dev/null
 
-if type "composer" &> /dev/null; then
-    msg 'Cleaning up composer...'
-    composer clearcache &>/dev/null
+if type "composer" &>/dev/null; then
+	msg 'Cleaning up composer...'
+	composer clearcache &>/dev/null
 fi
 
 if type "brew" &>/dev/null; then
-    if [ "$update" = true ]; then
-        msg 'Updating Homebrew Recipes...'
-        brew update &>/dev/null
-        msg 'Upgrading and removing outdated formulae...'
-        brew upgrade &>/dev/null
-    fi
-    msg 'Cleaning up Homebrew Cache...'
-    brew cleanup -s &>/dev/null
-    rm -rfv "$(brew --cache)" 
-    brew tap --repair &>/dev/null
+	if [ "$update" = true ]; then
+		msg 'Updating Homebrew Recipes...'
+		brew update &>/dev/null
+		msg 'Upgrading and removing outdated formulae...'
+		brew upgrade &>/dev/null
+	fi
+	msg 'Cleaning up Homebrew Cache...'
+	brew cleanup -s &>/dev/null
+	rm -rfv "$(brew --cache)"
+	brew tap --repair &>/dev/null
 fi
 
-if type "gem" &> /dev/null; then
-    msg 'Cleaning up any old versions of gems'
-    gem cleanup &>/dev/null
+if type "gem" &>/dev/null; then
+	msg 'Cleaning up any old versions of gems'
+	gem cleanup &>/dev/null
 fi
 
-if type "docker" &> /dev/null; then
-    msg 'Cleaning up Docker'
-    docker system prune -af &>/dev/null
+if type "docker" &>/dev/null; then
+	msg 'Cleaning up Docker'
+	docker system prune -af &>/dev/null
 fi
 
 if [ "$PYENV_VIRTUALENV_CACHE_PATH" ]; then
-    msg 'Removing Pyenv-VirtualEnv Cache...'
-    rm -rfv "$PYENV_VIRTUALENV_CACHE_PATH" &>/dev/null
+	msg 'Removing Pyenv-VirtualEnv Cache...'
+	rm -rfv "$PYENV_VIRTUALENV_CACHE_PATH" &>/dev/null
 fi
 
-if type "npm" &> /dev/null; then
-    msg 'Cleaning up npm cache...'
-    npm cache clean --force &>/dev/null
+if type "npm" &>/dev/null; then
+	msg 'Cleaning up npm cache...'
+	npm cache clean --force &>/dev/null
 fi
 
-if type "yarn" &> /dev/null; then
-    msg 'Cleaning up Yarn Cache...'
-    yarn cache clean --force &>/dev/null
+if type "yarn" &>/dev/null; then
+	msg 'Cleaning up Yarn Cache...'
+	yarn cache clean --force &>/dev/null
 fi
 
 msg 'Cleaning up DNS cache...'
